// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaMBK9sPVLs_C3uYsHm2VFE3O70cwmk0o',
    appId: '1:37076963723:web:5348214765de643fef5f8e',
    messagingSenderId: '37076963723',
    projectId: 'base-de-datos-caj',
    authDomain: 'base-de-datos-caj.firebaseapp.com',
    storageBucket: 'base-de-datos-caj.firebasestorage.app',
    measurementId: 'G-6CRPHSLEXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTJQniE7IF2Ttf_YWoVC_d7MCUicbT_nA',
    appId: '1:37076963723:android:a12d5a19874e6204ef5f8e',
    messagingSenderId: '37076963723',
    projectId: 'base-de-datos-caj',
    storageBucket: 'base-de-datos-caj.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6KILKC8ZB0P8BVJJvQI7rltMyHqYlD_A',
    appId: '1:37076963723:ios:0a3469616e462d16ef5f8e',
    messagingSenderId: '37076963723',
    projectId: 'base-de-datos-caj',
    storageBucket: 'base-de-datos-caj.firebasestorage.app',
    iosBundleId: 'com.example.controlturnos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6KILKC8ZB0P8BVJJvQI7rltMyHqYlD_A',
    appId: '1:37076963723:ios:0a3469616e462d16ef5f8e',
    messagingSenderId: '37076963723',
    projectId: 'base-de-datos-caj',
    storageBucket: 'base-de-datos-caj.firebasestorage.app',
    iosBundleId: 'com.example.controlturnos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaMBK9sPVLs_C3uYsHm2VFE3O70cwmk0o',
    appId: '1:37076963723:web:a229ce02e20ffa54ef5f8e',
    messagingSenderId: '37076963723',
    projectId: 'base-de-datos-caj',
    authDomain: 'base-de-datos-caj.firebaseapp.com',
    storageBucket: 'base-de-datos-caj.firebasestorage.app',
    measurementId: 'G-35RZXSDKPG',
  );
}
